openapi: 3.0.0
info:
  title: GraphQL API
  description: A simple example of a GraphQL API described with OpenAPI
  version: 1.0.0
paths:
  /graphql:
    post:
      summary: Execute a GraphQL query
      tags:
        - graphql
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                query:
                  type: string
                  description: |
                    The GraphQL query string. 
                    Format
                  
                    ```graphql
                    {
                      tableName(
                        column1Name: filter
                        column2Name: filter
                      ) {
                        column1Name
                        column2Name
                      }
                    }
                    ```
                    Filter
                    ```
                    {
                      "equals": value, 
                      "greaterThan": value, 
                      "greaterThanOrEquals": value,
                      "lessThan": value, 
                      "lessThanOrEquals": value, 
                      "between": {"start": value, "end": value}
                    }
                    ```
                  example: |
                    {
                      adventureGameHeroes(
                        joinDate: {between: {start: "2023-04-01", end: "2023-10-01"}}
                        occupation: {equals: "Warrior"}
                      ) {
                        id
                        joinDate
                        heroName
                        occupation
                        level
                        weaponName
                        weaponType
                        weaponPower
                        equipmentStatus
                      }
                    }
                variables:
                  type: object
                  description: Variables for the GraphQL query
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      tableName:
                        type: array
                        description: table
                        items:
                          type: object
                          properties:
                            columnName:
                              type: string
                              description: the value of this column
                    description: The data returned by the GraphQL query
                  errors:
                    type: array
                    items:
                      type: object
                      properties:
                        message:
                          type: string
                          description: The error message
                        locations:
                          type: array
                          items:
                            type: object
                            properties:
                              line:
                                type: integer
                                description: The line number of the error
                              column:
                                type: integer
                                description: The column number of the error
                        path:
                          type: array
                          items:
                            type: string
                          description: The path of the error
                example:
                  data:
                      adventureGameHeroes:
                        - id: 5
                          heroName: "Eowyn"
                          occupation: "Warrior"
                          level: 9
                          weaponName: "Golden Shield"
                          weaponType: "Shield"
                          weaponPower: 35.8
                          equipmentStatus: "Equipped"
                          joinDate: "2023-05-01"
                        - id: 9
                          heroName: "Boromir"
                          occupation: "Warrior"
                          level: 8
                          weaponName: "Gondorian Sword"
                          weaponType: "Sword"
                          weaponPower: 48.7
                          equipmentStatus: "Equipped"
                          joinDate: "2023-09-01"

servers:
  - url: http://localhost:8000
    description: Local server