openapi: 3.0.0
info:
  title: GraphQL API
  description: A simple example of a GraphQL API described with OpenAPI
  version: 1.0.0
paths:
  /graphql:
    post:
      summary: Execute a GraphQL query
      tags:
        - graphql
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                query:
                  type: string
                  description: |
                    The GraphQL query string. Format

                    ```graphql
                    {
                      table_name(
                        filter: {
                          column_name: {
                            filter_option
                          }
                        },
                        limit: int,
                        offset: int,
                        order_by: [
                          {
                            column: column_name,
                            order: ASC or DESC
                          }
                        ]
                      ) {
                        column1_name
                        column2_name
                      }
                    }
                    ```
                    Filter option
                    ```
                    {
                      "equals": value, 
                      "greater_than": value, 
                      "greater_than_or_equals": value,
                      "less_than": value, 
                      "less_than_or_equals": value, 
                      "between": {"start": value, "end": value}
                    }
                  example: |-
                    query {
                      adventure_game_heroes (
                        filter: {
                          join_date: {
                            between: {
                              start: "2023-04-01",
                              end: "2023-10-01"
                            }
                          },
                          occupation: {
                            equals: "Warrior"
                          }
                        },
                        limit: 3,
                        offset: 0,
                        order_by: [
                          {
                            column: "join_date",
                            order: ASC
                          }
                        ]
                      ) {
                        id,
                        join_date,
                        hero_name,
                        occupation,
                        level,
                        weapon_name,
                        weapon_type,
                        weapon_power,
                        equipment_status
                      }
                    }
                variables:
                  type: object
                  description: Variables for the GraphQL query
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      tableName:
                        type: array
                        description: table
                        items:
                          type: object
                          properties:
                            columnName:
                              type: string
                              description: the value of this column
                    description: The data returned by the GraphQL query
                  errors:
                    type: array
                    items:
                      type: object
                      properties:
                        message:
                          type: string
                          description: The error message
                        locations:
                          type: array
                          items:
                            type: object
                            properties:
                              line:
                                type: integer
                                description: The line number of the error
                              column:
                                type: integer
                                description: The column number of the error
                        path:
                          type: array
                          items:
                            type: string
                          description: The path of the error
                example:
                  data:
                    adventure_game_heroes:
                      - id: 5
                        join_date: '2023-05-01'
                        hero_name: Eowyn
                        occupation: Warrior
                        level: 9
                        weapon_name: Golden Shield
                        weapon_type: Shield
                        weapon_power: 35.8
                        equipment_status: Equipped
                      - id: 9
                        join_date: '2023-09-01'
                        hero_name: Boromir
                        occupation: Warrior
                        level: 8
                        weapon_name: Gondorian Sword
                        weapon_type: Sword
                        weapon_power: 48.7
                        equipment_status: Equipped
servers:
  - url: http://localhost:8000
    description: Local server